permalink: /:categories/:year/:month/:day/:title

exclude: [".rvmrc", ".rbenv-version", "ReadMe.md", "Rakefile", "changelog.md", "License.md"]

highlighter: rouge

title : Test Title

author :
  name : Anand Bhat
  email : anandbhat2509@gmail.com
  github : anand-bhat
  twitter : _anandbhat
  feedburner : nil

production_url : https://anand-bhat.github.io/test

markdown: kramdown

JB :
  version : 0.3.0
  BASE_PATH : https://anand-bhat.github.io/test
  archive_path: nil
  categories_path : nil
  tags_path : nil
  atom_path : nil
  rss_path : nil
  comments :
    provider : false
  analytics :
    provider : false
  sharing :
    provider : false
